server:
  port: 8002
  mode: dev

mysql:
  host: localhost
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  log_level: debug
  log_file_name: "./storages/logs/dev.003.log"
  max_size:    500
  max_backups: 3
  max_age:     28
  compress:   true

redis:
  host: localhost
  port: 6381
  password: 
  database: 0

smtp:
  host: smtp.gmail.com
  port: 587
  username: anh487303@gmail.com
  password: lwil xifg kovh blhh
