server:
  port: 1234
  mode: fake_mode

mysql:
  host: fake_mysql_host
  port: 1234
  username: fake_user
  password: fake_password
  dbname: fake_db
  maxIdleConns: 1
  maxOpenConns: 1
  connMaxLifetime: 1

logger:
  log_level: fake_level
  log_file_name: "./fake_path/fake.log"
  max_size:    1
  max_backups: 1
  max_age:     1
  compress:   false

redis:
  host: fake_redis_host
  port: 1234
  password: fake_password
  database: 1

smtp:
  host: fake_smtp_host
  port: 1234
  username: fake_email@example.com
  password: fake_password