server:
  port: 8080
  mode: dev

mysql:
  host: mysql
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  log_level: debug
  log_file_name: "./storages/logs/dev.003.log"
  max_size:    500
  max_backups: 3
  max_age:     28
  compress:   true

redis:
  host: redis
  port: 6379
  password: 
  database: 0